### ISSUE TITLE
hey我想知道如何上手citadel

### ISSUE THREAD

**Issue by baka4n** [EEEAB/EEEABsMobs#1]

**Comment by EEEAB** [comment]
我的话很简单，就是去参考其他同样使用了Citalde的优秀开源项目相关代码（例如Alex'Mobs、Ice And Fire等等），动画设计与制作是使用了Blockbench软件。

**Comment by baka4n** [comment]
> 我的话很简单，就是去参考其他同样使用了Citalde的优秀开源项目相关代码（例如Alex'Mobs、Ice And Fire等等），动画设计与制作是使用了Blockbench软件。

就是现在很多实例都是直接引向实体的方块实体的具体例子不知道在哪找

**Comment by baka4n** [comment]
看了你的部分代码我大概知晓了一些
