### ISSUE TITLE
Ticking Entity Error from Guardian Laser

### ISSUE THREAD

**Issue by Acenthus** [EEEAB/EEEABsMobs#11]
First off just wanna say I absolutely love this mod so far and feel like it has potential to being one of the best boss mods out there. 

Anyways getting attacked by the guardian's laser the world immediately closes saying "server closed"

[Crash pastebin](https://pastebin.com/PCTkNPSN)

**Comment by EEEAB** [comment]
For mod integration packs, you need to provide a detailed scenario: what the player was doing right before the crash, for example. I need to restore the crash scene because this mod runs alone on the server without any problems.

**Comment by EEEAB** [comment]
Or can you provide a download link for the mod package?

**Comment by Acenthus** [comment]
[Strikecraft-g1.6.0.zip](https://github.com/user-attachments/files/15832975/Strikecraft-g1.6.0.zip)
Sorry for the wait I didn't realize you'd respond so quickly.

**Comment by Acenthus** [comment]
Also should mention it's a modpack to be used in curseforge if you don't know.

**Comment by ERO-Dragon** [comment]
I meet a similar crash too. It's from my modpack, crashreport is attached. 
我的包也有人遇到了类似的问题，附上崩溃报告。我的包在cf上也有，有需要的话我可以提供链接。
[crash-2024-06-17_18.37.30-server (1).txt](https://github.com/user-attachments/files/15871009/crash-2024-06-17_18.37.30-server.1.txt)

**Comment by EEEAB** [comment]
> 我也遇到了类似的崩溃。这是来自我的 modpack，附有崩溃报告。 我的包也有人遇到了类似的问题，附上崩溃报告。我的包上也有，有需要的话我可以链接。 [crash-2024-06-17_18.37.30 -服务器（1）.txt](https://github.com/user-attachments/files/15871009/crash-2024-06-17_18.37.30-server.1.txt)
![image](https://github.com/EEEAB/EEEABsMobs/assets/124225968/506c4495-13d3-4677-bf35-8dea4421870a)

您提供的这个问题已经找到了，应该是使用守卫者核心发射激光的时候（身上护甲携带荆棘附魔）攻击多个古陵哨兵。因为古陵哨兵存在反伤，但逻辑没写对，导致内存溢出问题 。0.92版本更新会修复这个问题

**Comment by ERO-Dragon** [comment]
感谢您的回复与修复：）

**Comment by EEEAB** [comment]
> [Strikecraft-g1.6.0.zip](https://github.com/user-attachments/files/15832975/Strikecraft-g1.6.0.zip) 抱歉让您久等了，我没想到您回复得这么快。
Sorry, I can't run the modpack you provided in single player mode , is it because I opened it in a wrong way?

**Comment by Acenthus** [comment]
The modpack should be loaded using curseforge's create custom profile button then import a previously created profile, it'll ask for a zip file which is where you put that file. 
![image](https://github.com/EEEAB/EEEABsMobs/assets/85658662/61e06624-e9dd-450a-915b-054cecacb07b)
![image](https://github.com/EEEAB/EEEABsMobs/assets/85658662/8764fe4b-911f-4ff2-ba84-ffa02a2f285e)
