### ISSUE TITLE
All mobs are incompatible with a few mods that affect hostiles' behavior 

### ISSUE THREAD

**Issue by nameedo** [EEEAB/EEEABsMobs#12]
I have noticed that none of your mob are affected by those mods, probably because they are not considered hostile? 

If the purpose is making them not despawn in peaceful mode. What if you try to do it in a way like Cataclysm or Mowzie's Mobs? 

(These two mods mobs don't despawn in peaceful but also work with mods that affect behavior)

**Comment by EEEAB** [comment]
Uh, you mean creatures don't disappear in peace mode? Not sure what you're trying to say...

**Comment by nameedo** [comment]
Some mods change **hostiles** behavior, your mobs don't work

**Comment by EEEAB** [comment]
Can't add potion effects from other mods? Cataclysm mod Stun effect, Mowzie's Mobs Frozen effect?

**Comment by nameedo** [comment]
no no no
Do you know Champions mod? It lets you add "stuff" to hostiles. Eeeabs mobs do not work with that

**Comment by EEEAB** [comment]
Are only some mobs incompatible? Can you give me an example of that entity?

**Comment by nameedo** [comment]
Every mob is. 

One question, how did you make your mobs not despawn in peaceful difficulty?

**Comment by EEEAB** [comment]
I override the Mob.shouldDespawnInPeaceful() method to set the value to true

**Comment by nameedo** [comment]
Alright I'm unsure why your mobs don't seem to be "monsters" 

I believe Champions mod only works for monsters

Another example is Guard Villagers mod, none of your mobs are considered "monsters" by them

**Comment by EEEAB** [comment]
I have no idea at the moment, I have to look at the Champions mod source code, thank you for your feedback, I will add this issue to the mod development schedule :)

**Comment by nameedo** [comment]
whatever you did it worked! (latest commit)

**Comment by EEEAB** [comment]
Really?? I was surprised...

**Comment by nameedo** [comment]
Yeah it works great. The mod seems to work the same but compatible with others now.

The only change may be that immortal skeletons despawn in peaceful (the other immortal don't)

**Comment by EEEAB** [comment]
OK,I will correct the point you mentioned, at present these immortal mobs are unfinished :)
