### ISSUE TITLE
与Good Ending模组安装时，易崩溃。

### ISSUE THREAD

**Issue by 7yudinglaopin8** [EEEAB/EEEABsMobs#16]
与Good Ending模组安装时，拿出幽冥钢剑的时候，游戏就会崩溃。
[crash-2024-11-16_12.43.20-client.txt](https://github.com/user-attachments/files/17783560/crash-2024-11-16_12.43.20-client.txt)
（Good ending模组经常会在拿出剑类物品时崩溃。）

**Comment by EEEAB** [comment]
我在翻看这个模组的仓库时，发现早在去年有跟你这个日志中出现一样的错误，你可以尝试去[点我跳转](https://github.com/0rc1nus/GoodEnding/issues/7)

目前有一个可能可以解决的办法：在配置eeeabsmobs-common.toml文件中找到Ghost Warrior Series这一项，将Enable armor or weapon can be depleted设置为true

**Comment by EEEAB** [comment]
守卫者战斧是否也会出现一拿出来就崩溃的情况?

**Comment by 7yudinglaopin8** [comment]
我不到啊，我过会试试。
我又报了一遍https://github.com/0rc1nus/GoodEnding/issues/29
这个模组还会和其他剑有同样的崩溃效果，像是水产业2的海王剑，无尽贪婪的寰宇支配之剑，神圣RPG的狱火剑（不过后来的神圣RPG修了）。

**Comment by 7yudinglaopin8** [comment]
> 守卫者战斧是否也会出现一拿出来就崩溃的情况?

没有。

**Comment by EEEAB** [comment]
我复现了问题，并且将配置进行了修改，反而没有出现崩溃的问题了。
那看来是这个模组改动了物品中canBeDepleted方法，幽冥炼狱太刀有super父类的canBeDepleted方法这才导致的。
我不清楚具体的原因，其实应该解决这个问题的是这个模组，而不是让我来去对它的bug去做兼容。
既然这个模组都一年没有得到彻底的解决，我也只能去兼容了...苦笑

**Comment by 7yudinglaopin8** [comment]
> 我复现了问题，并且将配置进行了修改，反而没有出现崩溃的问题了。 那看来是这个模组改动了物品中canBeDepleted方法，幽冥炼狱太刀有super父类的canBeDepleted方法这才导致的。 我不清楚具体的原因，其实应该解决这个问题的是这个模组，而不是让我来去对它的bug去做兼容。 既然这个模组都一年没有得到彻底的解决，我也只能去兼容了...苦笑

OK，这个问题就这样吧。
