### ISSUE TITLE
Server closed bug

### ISSUE THREAD

**Issue by Sylthena** [EEEAB/EEEABsMobs#17]
[crash-2024-11-23_19.06.51-server.txt](https://github.com/user-attachments/files/17882087/crash-2024-11-23_19.06.51-server.txt)

Seems similar to the posts on the issues page about the laser and scorch attack causing the server to close.

**Comment by EEEAB** [comment]
Could you please provide the Forge version?

**Comment by EEEAB** [comment]
Is your modpack loader NeoForge?

**Comment by Sylthena** [comment]
Latest Neoforge version

**Comment by EEEAB** [comment]
...

> Latest Neoforge version

**Comment by EEEAB** [comment]
This mod currently does not support the NeoForge version. Even if you use some mods to make it compatible with Forge mods, I consider it unstable because the crash content is caused by the mod loader. I will not solve this issue, nor can I ...
