### ISSUE TITLE
大概是高版本forge提供了LivingBreatheEvent这个事件监听器，但是低版本的forge（如47.1.3）没有这个监听器，所以eeeab无法加载

### ISSUE THREAD

**Issue by pillowdrink** [EEEAB/EEEABsMobs#18]
[错误报告-2024-11-17_13.48.51.zip](https://github.com/user-attachments/files/18050964/-2024-11-17_13.48.51.zip)

**Comment by EEEAB** [comment]
查了下日志，只需把Forge版本升至47.1.7以上可解决问题

**Comment by 24876021** [comment]
> 查了下日志，只需把Forge版本升至47.1.7以上可解决问题

Forge版本47.3.22也会崩溃

**Comment by EEEAB** [comment]
> > 查了下日志，只需把Forge版本升至47.1.7以上可解决问题
> 
> Forge版本47.3.22也会崩溃

关于1.20.1-0.97版本我已还原了问题并验证解决，我把开发环境的缓存清了一次再重新打包就可以了
