### ISSUE TITLE
[Permission Request] Backport to 1.19.2

### ISSUE THREAD

**Issue by min2222** [EEEAB/EEEABsMobs#2]
can i backport this mod to 1.19.2?

**Comment by EEEAB** [comment]
Sorry,I plan to transplant version 1.19.2 in the near future:)

**Comment by min2222** [comment]
> Sorry,I plan to transplant version 1.19.2 in the near future:)

nah, i can finish it in just 1 day

**Comment by min2222** [comment]
> Sorry,I plan to transplant version 1.19.2 in the near future:)

finished
https://github.com/min2222/EEEABsMobs-1.19.2/releases/tag/1.19.2-2

**Comment by mightyjaffa12** [comment]
> > Sorry,I plan to transplant version 1.19.2 in the near future:)
> 
> finished https://github.com/min2222/EEEABsMobs-1.19.2/releases/tag/1.19.2-2

My god your a monster, keep backporting mods so I can keep stuffing them into my 1.19.2 modpack!11
