### ISSUE TITLE
Issues with Better 3rd Person and Shoulder Surfing

### ISSUE THREAD

**Issue by iamturtleneck** [EEEAB/EEEABsMobs#4]
i noticed that when using the better 3rd person and shoulder surfing mods, right-clicking with weapons from your mod or being hit by projectiles from your mod cause the camera to return to the vanilla f5 angle for a few seconds before returning to normal. is it possible for you to fix this?

**Comment by EEEAB** [comment]
Thanks for the feedback, I'll do my best to fix it.

**Comment by EEEAB** [comment]
There is a temporary solution: find "eeeabsmobs-common.toml" in the config directory and change one of the options "Enable camera shake" to false.

**Comment by EEEAB** [comment]
I simulated the problem you mentioned, which only occurs when the two mods coexist, and I also tested other mods with wobbly camera angles and the same problem occurred. This kind of multimodule compatibility is difficult to resolve :<
