### ISSUE TITLE
[1.20.1] Rendering Entity Crash

### ISSUE THREAD

**Issue by RedBeast1959** [EEEAB/EEEABsMobs#6]
Forge 1.20.1 - 47.2.20
eeeabsmobs-1.20.1-0.5.jar

Crash during boss laser firing

[crash-2024-01-24_03.06.18-client.txt](https://github.com/EEEAB/EEEABsMobs/files/14028295/crash-2024-01-24_03.06.18-client.txt)

**Comment by EEEAB** [comment]
Thanks for the feedback! I offer a temporary solution: change the "Enable scorch generate" option in the configuration file "eeeabsmobs.common.toml" to false
